//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/myRouting/MyRoutingControl.msg.
//

#ifndef _MYROUTINGCONTROL_M_H_
#define _MYROUTINGCONTROL_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>src/node/communication/routing/myRouting/MyRoutingControl.msg:13</tt> by nedtool.
 * <pre>
 * enum MyRoutingControlDef
 * {
 * 
 *     MPRINGS_NOT_CONNECTED = 1;
 *     MPRINGS_CONNECTED_TO_TREE = 2;
 *     MPRINGS_TREE_LEVEL_UPDATED = 3;
 * }
 * </pre>
 */
enum MyRoutingControlDef {
    MPRINGS_NOT_CONNECTED = 1,
    MPRINGS_CONNECTED_TO_TREE = 2,
    MPRINGS_TREE_LEVEL_UPDATED = 3
};

/**
 * Class generated from <tt>src/node/communication/routing/myRouting/MyRoutingControl.msg:19</tt> by nedtool.
 * <pre>
 * message MyRoutingControlMessage
 * {
 *     int MyRoutingControlMessageKind @enum(MyRoutingControlDef);
 *     int sinkID;
 *     int level;
 * }
 * </pre>
 */
class MyRoutingControlMessage : public ::cMessage
{
  protected:
    int MyRoutingControlMessageKind_var;
    int sinkID_var;
    int level_var;

  private:
    void copy(const MyRoutingControlMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MyRoutingControlMessage&);

  public:
    MyRoutingControlMessage(const char *name=NULL, int kind=0);
    MyRoutingControlMessage(const MyRoutingControlMessage& other);
    virtual ~MyRoutingControlMessage();
    MyRoutingControlMessage& operator=(const MyRoutingControlMessage& other);
    virtual MyRoutingControlMessage *dup() const {return new MyRoutingControlMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getMyRoutingControlMessageKind() const;
    virtual void setMyRoutingControlMessageKind(int MyRoutingControlMessageKind);
    virtual int getSinkID() const;
    virtual void setSinkID(int sinkID);
    virtual int getLevel() const;
    virtual void setLevel(int level);
};

inline void doPacking(cCommBuffer *b, MyRoutingControlMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MyRoutingControlMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef _MYROUTINGCONTROL_M_H_

